### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by ultimateshadsform** [unjs/magic-regexp#412]
### 🐛 The bug

![image](https://github.com/user-attachments/assets/c093874e-01ca-4d82-800a-42795bbaf953)

Fix the docs page?

Chrome Version 128.0.6613.139 (Official Build) (64-bit)

![image](https://github.com/user-attachments/assets/504d1be2-df58-4477-a0a5-ffba97fd5e0a)

### 🛠️ To reproduce

https://regexp.dev/

### 🌈 Expected behaviour

See documentation

**Comment by ultimateshadsform** [comment]
Full console:

```txt
Ck2Ce_si.js:14 TypeError: Cannot read properties of null (reading 'map')
    at Ig (Ck2Ce_si.js:49:89184)
    at Ck2Ce_si.js:49:89756
    at gl.fn (Ck2Ce_si.js:10:9114)
    at gl.run (Ck2Ce_si.js:10:1517)
    at get value (Ck2Ce_si.js:10:9359)
    at ld.get (Ck2Ce_si.js:10:4633)
    at Ck2Ce_si.js:49:90907
    at r (Ck2Ce_si.js:14:3026)
    at be (Ck2Ce_si.js:14:20109)
    at Ck2Ce_si.js:49:86661

Ck2Ce_si.js:18 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Ck2Ce_si.js:14 TypeError: Cannot read properties of null (reading 'heroSubtitle')
    at setup (DcF9s4nD.js:83:200495)
Ck2Ce_si.js:14 TypeError: Cannot read properties of null (reading 'map')
    at Ig (Ck2Ce_si.js:49:89184)
    at Ck2Ce_si.js:49:89756
    at gl.fn (Ck2Ce_si.js:10:9114)
    at gl.run (Ck2Ce_si.js:10:1517)
    at get value (Ck2Ce_si.js:10:9359)
    at ld.get (Ck2Ce_si.js:10:4633)
    at Ck2Ce_si.js:49:90907
    at r (Ck2Ce_si.js:14:3026)
    at be (Ck2Ce_si.js:14:20109)
    at Ck2Ce_si.js:49:86661
Ck2Ce_si.js:18 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by danielroe** [comment]
Thank you!
